### ISSUE TITLE
YouTube module embeds a black screen

### ISSUE THREAD

**Issue by BrooklinJazz** [jonatanklosko/kino_lab#3]
This project is awesome! I'd love to be able to embed youtube videos into my livebooks. Please let me know if I can support the project in any way!

I seem to get a black screen whenever I use the `Kino.YouTube` module.
I've tried making my own Kino.JS module with a copy-pasted iframe (that works in a codepen) and got the same result.

I know this is an experimental project, so before I go debugging, is this a bug on my end, or the current behavior?

**Comment by jonatanklosko** [comment]
@BrooklinJazz please try with Livebook main :) It has a number of fixes we made that make sure the iframe has all the necessary privileges and is still sandboxed.

**Comment by BrooklinJazz** [comment]
That worked! Thank you Jonatan :D
